export const cuisineList = [
    "North Indian",
    "South Indian",
    "Maharashtrian",
    "Gujarati",
    "Rajasthani",
    "Punjabi",
    "Mughlai",
    "Bengali",
    "Street Food",
    "Chinese",
    "Thai",
    "Japanese",
    "Korean",
    "Vietnamese",
    "Asian Fusion",
    "Italian",
    "French",
    "Spanish",
    "Greek",
    "Continental",
    "American",
    "Mexican",
    "Tex-Mex",
    "BBQ",
    "Burgers",
    "Fast Food",
    "Cafe",
    "Bakery",
    "Desserts",
    "Ice Cream",
    "Beverages",
    "Healthy",
    "Salads",
    "Vegan",
    "Organic",
    "Gluten-Free",
    "Breakfast",
    "Lunch",
    "Dinner",
    "Snacks",
];
